apiVersion: meta.pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-eapi
  annotations:
    meta.crossplane.io/source: https://github.com/netclab/function-eapi
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: Configure Arista EOS devices via JSON-RPC.
    meta.crossplane.io/readme: |
      This Crossplane composition function generates resources for interacting with Arista EOS devices via JSON-RPC.
      It is intended for use with netclab-xp configuration package to manage device configuration automatically.
spec:
  crossplane:
    version: ">=v2.1.1"
